### ISSUE TITLE
Not an issue, but a new useful feature... 

### ISSUE THREAD

**Issue by jasonkirk-tech** [nbelyh/VisioOnlineSpfxWebPart#4]
Really love this. I am not sure how easy it is to add it, but do you have the ability to make the Ctrl + Click for hyperlinks a click only experience? I am not sure if it's possible via etc SPFx. 

Do you have plans to develop this further?

**Comment by nbelyh** [comment]
I'm open to adding features, just when I have time, but yes, it's not forgotten 😅 
The problem with Ctrl + Click is that this web part is just embedding Visio Online, showing some otherwise "hidden" options. Using this web part, it's not possible to modify its behavior, only to "customize" the stock one a bit.

**Comment by nbelyh** [comment]
Now "click only" selects shapes. It is not possible to have it in the web part, this behavior is dctated by the underlying Visio Online renderer.
